### ISSUE TITLE
gdata wants atom.LinkFinder but atom 0.3.5 or 0.3.6 doesn't have this, gdata doesn't work with atom >= 0.3.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [carolinux/gdata-python-client#689]
```
Hello, I have gdata 2.0.18 instaled with my python 2.7.5. I have atom library 
version below 0.3.5 and all works well. But when I upgrade atom library to 
version 0.3.5 or 0.3.6 these code

import atom
import gdata.calendar

raise this error

Traceback (most recent call last):
  File "C:\Users\Booker\YandexDisk\workspace\sms\sms_from_google_calendar.py", line 3, in <module>
    import gdata.calendar
  File "C:\Python27\lib\site-packages\gdata\__init__.py", line 109, in <module>
    class LinkFinder(atom.LinkFinder):
AttributeError: 'module' object has no attribute 'LinkFinder'

Atom library of 0.3.5 doesn't have atom.LinkFinder. I want to use previos 
version of atom lybrary but there is no distributions!

for example 

pip install atom == 0.3.1

says that available only 0.3.5 and 0.3.6 version !

gdata wants atom.LinkFinder for their work but atom available by pipy doesn't 
have thise what can I do ?
```

Original issue reported on code.google.com by `med.phis...@gmail.com` on 27 Jan 2014 at 1:58

**Comment by bbaros** [comment]
Uninstalling Atom only didn't help.  Uninstalling and reinstalling gdata after uninstalling Atom worked.

**Comment by ossarotte** [comment]
i try to uninstall atom under Anaconda but nothing change
but when i try to reinstall
(C:\ProgramData\Anaconda2) c:\workarea\python\gdata-python-client-master>python setup.py install
C:\ProgramData\Anaconda2\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing C:\ProgramData\Anaconda2\Lib\site-packages\gdata-2.0.18-py2.7.egg-info
Writing C:\ProgramData\Anaconda2\Lib\site-packages\gdata-2.0.18-py2.7.egg-info
