### ISSUE TITLE
Upgrading a session token with Python 2.5.2 causes exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [carolinux/gdata-python-client#161]
```
What steps will reproduce the problem?
1. I have a python script that accesses spreadsheet data
2. It sends the user to https://www.google.com/accounts/AuthSubRequest to
obtain a token, and uses the next parameter to redirect back to itself.
3. It detects the token and calls gd_client.UpgradeToSessionToken() to
upgrade this to a session token.
4. From there the call trace goes to gdata/service.py, atom/service.py to
the python 2.5 httplib.py where we get an exception in connect():

<type 'exceptions.AttributeError'>: 'module' object has no attribute 'socket'
      args = ("'module' object has no attribute 'socket'",)
      message = "'module' object has no attribute 'socket'" 

This seems to work on Python 2.4 (although I can confirm that later). 
Python 2.5 is needed because I'm trying to get this into Google AppEngine
(it's deployed but non-functioning).
```

Original issue reported on code.google.com by `drinc...@gmail.com` on 11 Sep 2008 at 8:50
